In [1]:
import pandas as pd
data=pd.read_csv('03_2010_df_625 Variables.csv')

In [2]:
data[data.Date<'2012-01-01'].shape

(35064, 625)

In [3]:
data = data.drop('Unnamed: 0',axis=1)

In [4]:
box=pd.read_csv('04_Box_Cox_load.csv',index_col=False)

In [5]:
box=box.drop('Unnamed: 0',axis=1)

In [6]:
box.index=pd.Int64Index(box.index)

In [7]:
data.index=pd.Int64Index(data.index)

In [8]:
box_data=pd.merge(data, box, left_on=data.index,right_on=box.index,how='left')

In [9]:
box_data = box_data.drop('key_0',axis=1)

In [10]:
box_data[box_data['Date']>='2011-12-31']

,Date,Hour,Temperature,Load,month,weekday,Distance,TemperatureLag1,TemperatureLag2,TemperatureLag24,...,holiday.temp_mean_6_0.5,holiday.temp_mean_6_2,holiday.temp_mean_6_3,holiday.temp_mean_12_0.5,holiday.temp_mean_12_2,holiday.temp_mean_12_3,holiday.temp_mean_24_0.5,holiday.temp_mean_24_2,holiday.temp_mean_24_3,box
35040,2011-12-31,1,35.33,9970.0,December,Saturday,16.67,34.00,36.33,32.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.788346
35041,2011-12-31,2,34.67,9428.0,December,Saturday,17.33,35.33,34.00,34.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.282733
35042,2011-12-31,3,33.67,9059.0,December,Saturday,18.33,34.67,35.33,35.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.925719
35043,2011-12-31,4,32.33,8817.0,December,Saturday,19.67,33.67,34.67,37.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.685532
35044,2011-12-31,5,30.67,8743.0,December,Saturday,21.33,32.33,33.67,37.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.611087
35045,2011-12-31,6,30.33,8735.0,December,Saturday,21.67,30.67,32.33,39.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.603010
35046,2011-12-31,7,29.67,8993.0,December,Saturday,22.33,30.33,30.67,39.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.860702
35047,2011-12-31,8,29.67,9363.0,December,Saturday,22.33,29.67,30.33,39.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.220625
35048,2011-12-31,9,32.00,9545.0,December,Saturday,20.00,29.67,29.67,40.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.393714
35049,2011-12-31,10,34.00,9676.0,December,Saturday,18.00,32.00,29.67,41.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.516753
35050,2011-12-31,11,35.67,9937.0,December,Saturday,16.33,34.00,32.00,42.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.758167
35051,2011-12-31,12,35.00,10139.0,December,Saturday,17.00,35.67,34.00,42.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.941720
35052,2011-12-31,13,35.33,10326.0,December,Saturday,16.67,35.00,35.67,43.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.109183
35053,2011-12-31,14,36.67,10359.0,December,Saturday,15.33,35.33,35.00,43.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.138495
35054,2011-12-31,15,37.33,10293.0,December,Saturday,14.67,36.67,35.33,43.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.079799
35055,2011-12-31,16,37.67,10240.0,December,Saturday,14.33,37.33,36.67,43.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.032457
35056,2011-12-31,17,37.67,10416.0,December,Saturday,14.33,37.67,37.33,41.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.188959
35057,2011-12-31,18,38.67,11225.0,December,Saturday,13.33,37.67,37.67,40.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.883515
35058,2011-12-31,19,38.67,11907.0,December,Saturday,13.33,38.67,37.67,39.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.440057
35059,2011-12-31,20,39.33,11812.0,December,Saturday,12.67,38.67,38.67,39.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.364010
35060,2011-12-31,21,39.33,11542.0,December,Saturday,12.67,39.33,38.67,38.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.145307
35061,2011-12-31,22,39.00,11149.0,December,Saturday,13.00,39.33,39.33,37.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.819917
35062,2011-12-31,23,39.33,10855.0,December,Saturday,12.67,39.00,39.33,36.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.570746
35063,2011-12-31,24,39.00,10335.0,December,Saturday,13.00,39.33,39.00,34.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.117184
35064,2012-01-01,1,39.33,NaN,January,Sunday,12.67,39.00,39.33,35.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35065,2012-01-01,2,40.33,NaN,January,Sunday,11.67,39.33,39.00,34.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35066,2012-01-01,3,39.67,NaN,January,Sunday,12.33,40.33,39.33,33.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35067,2012-01-01,4,42.33,NaN,January,Sunday,9.67,39.67,40.33,32.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35068,2012-01-01,5,43.00,NaN,January,Sunday,9.00,42.33,39.67,30.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35069,2012-01-01,6,42.00,NaN,January,Sunday,10.00,43.00,42.33,30.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43818,2012-12-30,19,29.67,NaN,December,Sunday,22.33,28.67,28.67,23.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43819,2012-12-30,20,30.67,NaN,December,Sunday,21.33,29.67,28.67,22.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43820,2012-12-30,21,31.33,NaN,December,Sunday,20.67,30.67,29.67,21.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43821,2012-12-30,22,31.67,NaN,December,Sunday,20.33,31.33,30.67,20.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43822,2012-12-30,23,31.67,NaN,December,Sunday,20.33,31.67,31.33,19.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43823,2012-12-30,24,26.67,NaN,December,Sunday,25.33,31.67,31.67,21.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43824,2012-12-31,1,30.67,NaN,December,Monday,21.33,26.67,31.67,16.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43825,2012-12-31,2,31.67,NaN,December,Monday,20.33,30.67,26.67,15.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43826,2012-12-31,3,32.33,NaN,December,Monday,19.67,31.67,30.67,14.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43827,2012-12-31,4,33.00,NaN,December,Monday,19.00,32.33,31.67,13.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43828,2012-12-31,5,33.33,NaN,December,Monday,18.67,33.00,32.33,13.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43829,2012-12-31,6,33.33,NaN,December,Monday,18.67,33.33,33.00,13.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43830,2012-12-31,7,33.00,NaN,December,Monday,19.00,33.33,33.33,12.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43831,2012-12-31,8,32.67,NaN,December,Monday,19.33,33.00,33.33,12.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43832,2012-12-31,9,32.67,NaN,December,Monday,19.33,32.67,33.00,16.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43833,2012-12-31,10,32.00,NaN,December,Monday,20.00,32.67,32.67,20.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43834,2012-12-31,11,31.00,NaN,December,Monday,21.00,32.00,32.67,23.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43835,2012-12-31,12,30.33,NaN,December,Monday,21.67,31.00,32.00,26.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43836,2012-12-31,13,29.00,NaN,December,Monday,23.00,30.33,31.00,29.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43837,2012-12-31,14,28.33,NaN,December,Monday,23.67,29.00,30.33,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43838,2012-12-31,15,26.67,NaN,December,Monday,25.33,28.33,29.00,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43839,2012-12-31,16,26.00,NaN,December,Monday,26.00,26.67,28.33,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43840,2012-12-31,17,24.33,NaN,December,Monday,27.67,26.00,26.67,28.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43841,2012-12-31,18,24.00,NaN,December,Monday,28.00,24.33,26.00,28.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43842,2012-12-31,19,23.33,NaN,December,Monday,28.67,24.00,24.33,29.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43843,2012-12-31,20,22.33,NaN,December,Monday,29.67,23.33,24.00,30.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43844,2012-12-31,21,20.67,NaN,December,Monday,31.33,22.33,23.33,31.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43845,2012-12-31,22,19.67,NaN,December,Monday,32.33,20.67,22.33,31.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43846,2012-12-31,23,19.33,NaN,December,Monday,32.67,19.67,20.67,31.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43847,2012-12-31,24,18.33,NaN,December,Monday,33.67,19.33,19.67,26.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [11]:
box_data.columns.values

array(['Date', 'Hour', 'Temperature', 'Load', 'month', 'weekday',
       'Distance', 'TemperatureLag1', 'TemperatureLag2',
       'TemperatureLag24', 'TemperatureLag48', 'Temperature_2_Lag',
       'Temperature_2_Lag1', 'Temperature_2_Lag2', 'Temperature_2_Lag24',
       'Temperature_2_Lag48', 'Temperature_3_Lag', 'Temperature_3_Lag1',
       'Temperature_3_Lag2', 'Temperature_3_Lag24', 'Temperature_3_Lag48',
       'Temperature_0.5_Lag', 'Temperature_0.5_Lag1',
       'Temperature_0.5_Lag2', 'Temperature_0.5_Lag24',
       'Temperature_0.5_Lag48', 'DistanceLag1', 'DistanceLag2',
       'DistanceLag24', 'DistanceLag48', 'Distance_2_Lag',
       'Distance_2_Lag1', 'Distance_2_Lag2', 'Distance_2_Lag24',
       'Distance_2_Lag48', 'Distance_3_Lag', 'Distance_3_Lag1',
       'Distance_3_Lag2', 'Distance_3_Lag24', 'Distance_3_Lag48',
       'Distance_0.5_Lag', 'Distance_0.5_Lag1', 'Distance_0.5_Lag2',
       'Distance_0.5_Lag24', 'Distance_0.5_Lag48', 'day', 'month.week',
       'quarter', 'temp_max_6', 'temp_max_12', 'temp_max_24',
       'temp_min_6', 'temp_min_12', 'temp_min_24', 'temp_std_6',
       'temp_std_12', 'temp_std_24', 'temp_mean_6', 'temp_mean_12',
       'temp_mean_24', 'Hour_Mean_Encoding', 'month_Mean_Encoding',
       'quarter_Mean_Encoding', 'weekday_Mean_Encoding',
       'month.week_Mean_Encoding', 'holiday', 'temp_max_6_0.5',
       'temp_max_6_2', 'temp_max_6_3', 'temp_max_12_0.5', 'temp_max_12_2',
       'temp_max_12_3', 'temp_max_24_0.5', 'temp_max_24_2',
       'temp_max_24_3', 'temp_min_6_0.5', 'temp_min_6_2', 'temp_min_6_3',
       'temp_min_12_0.5', 'temp_min_12_2', 'temp_min_12_3',
       'temp_min_24_0.5', 'temp_min_24_2', 'temp_min_24_3',
       'temp_std_6_0.5', 'temp_std_6_2', 'temp_std_6_3',
       'temp_std_12_0.5', 'temp_std_12_2', 'temp_std_12_3',
       'temp_std_24_0.5', 'temp_std_24_2', 'temp_std_24_3',
       'temp_mean_6_0.5', 'temp_mean_6_2', 'temp_mean_6_3',
       'temp_mean_12_0.5', 'temp_mean_12_2', 'temp_mean_12_3',
       'temp_mean_24_0.5', 'temp_mean_24_2', 'temp_mean_24_3',
       'Hour_Mean_Encoding.Distance',
       'Hour_Mean_Encoding.TemperatureLag1',
       'Hour_Mean_Encoding.TemperatureLag2',
       'Hour_Mean_Encoding.TemperatureLag24',
       'Hour_Mean_Encoding.TemperatureLag48',
       'Hour_Mean_Encoding.Temperature_2_Lag',
       'Hour_Mean_Encoding.Temperature_2_Lag1',
       'Hour_Mean_Encoding.Temperature_2_Lag2',
       'Hour_Mean_Encoding.Temperature_2_Lag24',
       'Hour_Mean_Encoding.Temperature_2_Lag48',
       'Hour_Mean_Encoding.Temperature_3_Lag',
       'Hour_Mean_Encoding.Temperature_3_Lag1',
       'Hour_Mean_Encoding.Temperature_3_Lag2',
       'Hour_Mean_Encoding.Temperature_3_Lag24',
       'Hour_Mean_Encoding.Temperature_3_Lag48',
       'Hour_Mean_Encoding.Temperature_0.5_Lag',
       'Hour_Mean_Encoding.Temperature_0.5_Lag1',
       'Hour_Mean_Encoding.Temperature_0.5_Lag2',
       'Hour_Mean_Encoding.Temperature_0.5_Lag24',
       'Hour_Mean_Encoding.Temperature_0.5_Lag48',
       'Hour_Mean_Encoding.DistanceLag1',
       'Hour_Mean_Encoding.DistanceLag2',
       'Hour_Mean_Encoding.DistanceLag24',
       'Hour_Mean_Encoding.DistanceLag48',
       'Hour_Mean_Encoding.Distance_2_Lag',
       'Hour_Mean_Encoding.Distance_2_Lag1',
       'Hour_Mean_Encoding.Distance_2_Lag2',
       'Hour_Mean_Encoding.Distance_2_Lag24',
       'Hour_Mean_Encoding.Distance_2_Lag48',
       'Hour_Mean_Encoding.Distance_3_Lag',
       'Hour_Mean_Encoding.Distance_3_Lag1',
       'Hour_Mean_Encoding.Distance_3_Lag2',
       'Hour_Mean_Encoding.Distance_3_Lag24',
       'Hour_Mean_Encoding.Distance_3_Lag48',
       'Hour_Mean_Encoding.Distance_0.5_Lag',
       'Hour_Mean_Encoding.Distance_0.5_Lag1',
       'Hour_Mean_Encoding.Distance_0.5_Lag2',
       'Hour_Mean_Encoding.Distance_0.5_Lag24',
       'Hour_Mean_Encoding.Distance_0.5_Lag48',
       'Hour_Mean_Encoding.temp_max_6', 'Hour_Mean_Encoding.temp_max_12',
       'Hour_Mean_Encoding.temp_max_24', 'Hour_Mean_Encoding.temp_min_6',
       'Hour_Mean_Encoding.temp_min_12', 'Hour_Mean_Encoding.temp_min_24',
       'Hour_Mean_Encoding.temp_std_6', 'Hour_Mean_Encoding.temp_std_12',
       'Hour_Mean_Encoding.temp_std_24', 'Hour_Mean_Encoding.temp_mean_6',
       'Hour_Mean_Encoding.temp_mean_12',
       'Hour_Mean_Encoding.temp_mean_24',
       'Hour_Mean_Encoding.temp_max_6_0.5',
       'Hour_Mean_Encoding.temp_max_6_2',
       'Hour_Mean_Encoding.temp_max_6_3',
       'Hour_Mean_Encoding.temp_max_12_0.5',
       'Hour_Mean_Encoding.temp_max_12_2',
       'Hour_Mean_Encoding.temp_max_12_3',
       'Hour_Mean_Encoding.temp_max_24_0.5',
       'Hour_Mean_Encoding.temp_max_24_2',
       'Hour_Mean_Encoding.temp_max_24_3',
       'Hour_Mean_Encoding.temp_min_6_0.5',
       'Hour_Mean_Encoding.temp_min_6_2',
       'Hour_Mean_Encoding.temp_min_6_3',
       'Hour_Mean_Encoding.temp_min_12_0.5',
       'Hour_Mean_Encoding.temp_min_12_2',
       'Hour_Mean_Encoding.temp_min_12_3',
       'Hour_Mean_Encoding.temp_min_24_0.5',
       'Hour_Mean_Encoding.temp_min_24_2',
       'Hour_Mean_Encoding.temp_min_24_3',
       'Hour_Mean_Encoding.temp_std_6_0.5',
       'Hour_Mean_Encoding.temp_std_6_2',
       'Hour_Mean_Encoding.temp_std_6_3',
       'Hour_Mean_Encoding.temp_std_12_0.5',
       'Hour_Mean_Encoding.temp_std_12_2',
       'Hour_Mean_Encoding.temp_std_12_3',
       'Hour_Mean_Encoding.temp_std_24_0.5',
       'Hour_Mean_Encoding.temp_std_24_2',
       'Hour_Mean_Encoding.temp_std_24_3',
       'Hour_Mean_Encoding.temp_mean_6_0.5',
       'Hour_Mean_Encoding.temp_mean_6_2',
       'Hour_Mean_Encoding.temp_mean_6_3',
       'Hour_Mean_Encoding.temp_mean_12_0.5',
       'Hour_Mean_Encoding.temp_mean_12_2',
       'Hour_Mean_Encoding.temp_mean_12_3',
       'Hour_Mean_Encoding.temp_mean_24_0.5',
       'Hour_Mean_Encoding.temp_mean_24_2',
       'Hour_Mean_Encoding.temp_mean_24_3',
       'month_Mean_Encoding.Distance',
       'month_Mean_Encoding.TemperatureLag1',
       'month_Mean_Encoding.TemperatureLag2',
       'month_Mean_Encoding.TemperatureLag24',
       'month_Mean_Encoding.TemperatureLag48',
       'month_Mean_Encoding.Temperature_2_Lag',
       'month_Mean_Encoding.Temperature_2_Lag1',
       'month_Mean_Encoding.Temperature_2_Lag2',
       'month_Mean_Encoding.Temperature_2_Lag24',
       'month_Mean_Encoding.Temperature_2_Lag48',
       'month_Mean_Encoding.Temperature_3_Lag',
       'month_Mean_Encoding.Temperature_3_Lag1',
       'month_Mean_Encoding.Temperature_3_Lag2',
       'month_Mean_Encoding.Temperature_3_Lag24',
       'month_Mean_Encoding.Temperature_3_Lag48',
       'month_Mean_Encoding.Temperature_0.5_Lag',
       'month_Mean_Encoding.Temperature_0.5_Lag1',
       'month_Mean_Encoding.Temperature_0.5_Lag2',
       'month_Mean_Encoding.Temperature_0.5_Lag24',
       'month_Mean_Encoding.Temperature_0.5_Lag48',
       'month_Mean_Encoding.DistanceLag1',
       'month_Mean_Encoding.DistanceLag2',
       'month_Mean_Encoding.DistanceLag24',
       'month_Mean_Encoding.DistanceLag48',
       'month_Mean_Encoding.Distance_2_Lag',
       'month_Mean_Encoding.Distance_2_Lag1',
       'month_Mean_Encoding.Distance_2_Lag2',
       'month_Mean_Encoding.Distance_2_Lag24',
       'month_Mean_Encoding.Distance_2_Lag48',
       'month_Mean_Encoding.Distance_3_Lag',
       'month_Mean_Encoding.Distance_3_Lag1',
       'month_Mean_Encoding.Distance_3_Lag2',
       'month_Mean_Encoding.Distance_3_Lag24',
       'month_Mean_Encoding.Distance_3_Lag48',
       'month_Mean_Encoding.Distance_0.5_Lag',
       'month_Mean_Encoding.Distance_0.5_Lag1',
       'month_Mean_Encoding.Distance_0.5_Lag2',
       'month_Mean_Encoding.Distance_0.5_Lag24',
       'month_Mean_Encoding.Distance_0.5_Lag48',
       'month_Mean_Encoding.temp_max_6',
       'month_Mean_Encoding.temp_max_12',
       'month_Mean_Encoding.temp_max_24',
       'month_Mean_Encoding.temp_min_6',
       'month_Mean_Encoding.temp_min_12',
       'month_Mean_Encoding.temp_min_24',
       'month_Mean_Encoding.temp_std_6',
       'month_Mean_Encoding.temp_std_12',
       'month_Mean_Encoding.temp_std_24',
       'month_Mean_Encoding.temp_mean_6',
       'month_Mean_Encoding.temp_mean_12',
       'month_Mean_Encoding.temp_mean_24',
       'month_Mean_Encoding.temp_max_6_0.5',
       'month_Mean_Encoding.temp_max_6_2',
       'month_Mean_Encoding.temp_max_6_3',
       'month_Mean_Encoding.temp_max_12_0.5',
       'month_Mean_Encoding.temp_max_12_2',
       'month_Mean_Encoding.temp_max_12_3',
       'month_Mean_Encoding.temp_max_24_0.5',
       'month_Mean_Encoding.temp_max_24_2',
       'month_Mean_Encoding.temp_max_24_3',
       'month_Mean_Encoding.temp_min_6_0.5',
       'month_Mean_Encoding.temp_min_6_2',
       'month_Mean_Encoding.temp_min_6_3',
       'month_Mean_Encoding.temp_min_12_0.5',
       'month_Mean_Encoding.temp_min_12_2',
       'month_Mean_Encoding.temp_min_12_3',
       'month_Mean_Encoding.temp_min_24_0.5',
       'month_Mean_Encoding.temp_min_24_2',
       'month_Mean_Encoding.temp_min_24_3',
       'month_Mean_Encoding.temp_std_6_0.5',
       'month_Mean_Encoding.temp_std_6_2',
       'month_Mean_Encoding.temp_std_6_3',
       'month_Mean_Encoding.temp_std_12_0.5',
       'month_Mean_Encoding.temp_std_12_2',
       'month_Mean_Encoding.temp_std_12_3',
       'month_Mean_Encoding.temp_std_24_0.5',
       'month_Mean_Encoding.temp_std_24_2',
       'month_Mean_Encoding.temp_std_24_3',
       'month_Mean_Encoding.temp_mean_6_0.5',
       'month_Mean_Encoding.temp_mean_6_2',
       'month_Mean_Encoding.temp_mean_6_3',
       'month_Mean_Encoding.temp_mean_12_0.5',
       'month_Mean_Encoding.temp_mean_12_2',
       'month_Mean_Encoding.temp_mean_12_3',
       'month_Mean_Encoding.temp_mean_24_0.5',
       'month_Mean_Encoding.temp_mean_24_2',
       'month_Mean_Encoding.temp_mean_24_3',
       'quarter_Mean_Encoding.Distance',
       'quarter_Mean_Encoding.TemperatureLag1',
       'quarter_Mean_Encoding.TemperatureLag2',
       'quarter_Mean_Encoding.TemperatureLag24',
       'quarter_Mean_Encoding.TemperatureLag48',
       'quarter_Mean_Encoding.Temperature_2_Lag',
       'quarter_Mean_Encoding.Temperature_2_Lag1',
       'quarter_Mean_Encoding.Temperature_2_Lag2',
       'quarter_Mean_Encoding.Temperature_2_Lag24',
       'quarter_Mean_Encoding.Temperature_2_Lag48',
       'quarter_Mean_Encoding.Temperature_3_Lag',
       'quarter_Mean_Encoding.Temperature_3_Lag1',
       'quarter_Mean_Encoding.Temperature_3_Lag2',
       'quarter_Mean_Encoding.Temperature_3_Lag24',
       'quarter_Mean_Encoding.Temperature_3_Lag48',
       'quarter_Mean_Encoding.Temperature_0.5_Lag',
       'quarter_Mean_Encoding.Temperature_0.5_Lag1',
       'quarter_Mean_Encoding.Temperature_0.5_Lag2',
       'quarter_Mean_Encoding.Temperature_0.5_Lag24',
       'quarter_Mean_Encoding.Temperature_0.5_Lag48',
       'quarter_Mean_Encoding.DistanceLag1',
       'quarter_Mean_Encoding.DistanceLag2',
       'quarter_Mean_Encoding.DistanceLag24',
       'quarter_Mean_Encoding.DistanceLag48',
       'quarter_Mean_Encoding.Distance_2_Lag',
       'quarter_Mean_Encoding.Distance_2_Lag1',
       'quarter_Mean_Encoding.Distance_2_Lag2',
       'quarter_Mean_Encoding.Distance_2_Lag24',
       'quarter_Mean_Encoding.Distance_2_Lag48',
       'quarter_Mean_Encoding.Distance_3_Lag',
       'quarter_Mean_Encoding.Distance_3_Lag1',
       'quarter_Mean_Encoding.Distance_3_Lag2',
       'quarter_Mean_Encoding.Distance_3_Lag24',
       'quarter_Mean_Encoding.Distance_3_Lag48',
       'quarter_Mean_Encoding.Distance_0.5_Lag',
       'quarter_Mean_Encoding.Distance_0.5_Lag1',
       'quarter_Mean_Encoding.Distance_0.5_Lag2',
       'quarter_Mean_Encoding.Distance_0.5_Lag24',
       'quarter_Mean_Encoding.Distance_0.5_Lag48',
       'quarter_Mean_Encoding.temp_max_6',
       'quarter_Mean_Encoding.temp_max_12',
       'quarter_Mean_Encoding.temp_max_24',
       'quarter_Mean_Encoding.temp_min_6',
       'quarter_Mean_Encoding.temp_min_12',
       'quarter_Mean_Encoding.temp_min_24',
       'quarter_Mean_Encoding.temp_std_6',
       'quarter_Mean_Encoding.temp_std_12',
       'quarter_Mean_Encoding.temp_std_24',
       'quarter_Mean_Encoding.temp_mean_6',
       'quarter_Mean_Encoding.temp_mean_12',
       'quarter_Mean_Encoding.temp_mean_24',
       'quarter_Mean_Encoding.temp_max_6_0.5',
       'quarter_Mean_Encoding.temp_max_6_2',
       'quarter_Mean_Encoding.temp_max_6_3',
       'quarter_Mean_Encoding.temp_max_12_0.5',
       'quarter_Mean_Encoding.temp_max_12_2',
       'quarter_Mean_Encoding.temp_max_12_3',
       'quarter_Mean_Encoding.temp_max_24_0.5',
       'quarter_Mean_Encoding.temp_max_24_2',
       'quarter_Mean_Encoding.temp_max_24_3',
       'quarter_Mean_Encoding.temp_min_6_0.5',
       'quarter_Mean_Encoding.temp_min_6_2',
       'quarter_Mean_Encoding.temp_min_6_3',
       'quarter_Mean_Encoding.temp_min_12_0.5',
       'quarter_Mean_Encoding.temp_min_12_2',
       'quarter_Mean_Encoding.temp_min_12_3',
       'quarter_Mean_Encoding.temp_min_24_0.5',
       'quarter_Mean_Encoding.temp_min_24_2',
       'quarter_Mean_Encoding.temp_min_24_3',
       'quarter_Mean_Encoding.temp_std_6_0.5',
       'quarter_Mean_Encoding.temp_std_6_2',
       'quarter_Mean_Encoding.temp_std_6_3',
       'quarter_Mean_Encoding.temp_std_12_0.5',
       'quarter_Mean_Encoding.temp_std_12_2',
       'quarter_Mean_Encoding.temp_std_12_3',
       'quarter_Mean_Encoding.temp_std_24_0.5',
       'quarter_Mean_Encoding.temp_std_24_2',
       'quarter_Mean_Encoding.temp_std_24_3',
       'quarter_Mean_Encoding.temp_mean_6_0.5',
       'quarter_Mean_Encoding.temp_mean_6_2',
       'quarter_Mean_Encoding.temp_mean_6_3',
       'quarter_Mean_Encoding.temp_mean_12_0.5',
       'quarter_Mean_Encoding.temp_mean_12_2',
       'quarter_Mean_Encoding.temp_mean_12_3',
       'quarter_Mean_Encoding.temp_mean_24_0.5',
       'quarter_Mean_Encoding.temp_mean_24_2',
       'quarter_Mean_Encoding.temp_mean_24_3',
       'weekday_Mean_Encoding.Distance',
       'weekday_Mean_Encoding.TemperatureLag1',
       'weekday_Mean_Encoding.TemperatureLag2',
       'weekday_Mean_Encoding.TemperatureLag24',
       'weekday_Mean_Encoding.TemperatureLag48',
       'weekday_Mean_Encoding.Temperature_2_Lag',
       'weekday_Mean_Encoding.Temperature_2_Lag1',
       'weekday_Mean_Encoding.Temperature_2_Lag2',
       'weekday_Mean_Encoding.Temperature_2_Lag24',
       'weekday_Mean_Encoding.Temperature_2_Lag48',
       'weekday_Mean_Encoding.Temperature_3_Lag',
       'weekday_Mean_Encoding.Temperature_3_Lag1',
       'weekday_Mean_Encoding.Temperature_3_Lag2',
       'weekday_Mean_Encoding.Temperature_3_Lag24',
       'weekday_Mean_Encoding.Temperature_3_Lag48',
       'weekday_Mean_Encoding.Temperature_0.5_Lag',
       'weekday_Mean_Encoding.Temperature_0.5_Lag1',
       'weekday_Mean_Encoding.Temperature_0.5_Lag2',
       'weekday_Mean_Encoding.Temperature_0.5_Lag24',
       'weekday_Mean_Encoding.Temperature_0.5_Lag48',
       'weekday_Mean_Encoding.DistanceLag1',
       'weekday_Mean_Encoding.DistanceLag2',
       'weekday_Mean_Encoding.DistanceLag24',
       'weekday_Mean_Encoding.DistanceLag48',
       'weekday_Mean_Encoding.Distance_2_Lag',
       'weekday_Mean_Encoding.Distance_2_Lag1',
       'weekday_Mean_Encoding.Distance_2_Lag2',
       'weekday_Mean_Encoding.Distance_2_Lag24',
       'weekday_Mean_Encoding.Distance_2_Lag48',
       'weekday_Mean_Encoding.Distance_3_Lag',
       'weekday_Mean_Encoding.Distance_3_Lag1',
       'weekday_Mean_Encoding.Distance_3_Lag2',
       'weekday_Mean_Encoding.Distance_3_Lag24',
       'weekday_Mean_Encoding.Distance_3_Lag48',
       'weekday_Mean_Encoding.Distance_0.5_Lag',
       'weekday_Mean_Encoding.Distance_0.5_Lag1',
       'weekday_Mean_Encoding.Distance_0.5_Lag2',
       'weekday_Mean_Encoding.Distance_0.5_Lag24',
       'weekday_Mean_Encoding.Distance_0.5_Lag48',
       'weekday_Mean_Encoding.temp_max_6',
       'weekday_Mean_Encoding.temp_max_12',
       'weekday_Mean_Encoding.temp_max_24',
       'weekday_Mean_Encoding.temp_min_6',
       'weekday_Mean_Encoding.temp_min_12',
       'weekday_Mean_Encoding.temp_min_24',
       'weekday_Mean_Encoding.temp_std_6',
       'weekday_Mean_Encoding.temp_std_12',
       'weekday_Mean_Encoding.temp_std_24',
       'weekday_Mean_Encoding.temp_mean_6',
       'weekday_Mean_Encoding.temp_mean_12',
       'weekday_Mean_Encoding.temp_mean_24',
       'weekday_Mean_Encoding.temp_max_6_0.5',
       'weekday_Mean_Encoding.temp_max_6_2',
       'weekday_Mean_Encoding.temp_max_6_3',
       'weekday_Mean_Encoding.temp_max_12_0.5',
       'weekday_Mean_Encoding.temp_max_12_2',
       'weekday_Mean_Encoding.temp_max_12_3',
       'weekday_Mean_Encoding.temp_max_24_0.5',
       'weekday_Mean_Encoding.temp_max_24_2',
       'weekday_Mean_Encoding.temp_max_24_3',
       'weekday_Mean_Encoding.temp_min_6_0.5',
       'weekday_Mean_Encoding.temp_min_6_2',
       'weekday_Mean_Encoding.temp_min_6_3',
       'weekday_Mean_Encoding.temp_min_12_0.5',
       'weekday_Mean_Encoding.temp_min_12_2',
       'weekday_Mean_Encoding.temp_min_12_3',
       'weekday_Mean_Encoding.temp_min_24_0.5',
       'weekday_Mean_Encoding.temp_min_24_2',
       'weekday_Mean_Encoding.temp_min_24_3',
       'weekday_Mean_Encoding.temp_std_6_0.5',
       'weekday_Mean_Encoding.temp_std_6_2',
       'weekday_Mean_Encoding.temp_std_6_3',
       'weekday_Mean_Encoding.temp_std_12_0.5',
       'weekday_Mean_Encoding.temp_std_12_2',
       'weekday_Mean_Encoding.temp_std_12_3',
       'weekday_Mean_Encoding.temp_std_24_0.5',
       'weekday_Mean_Encoding.temp_std_24_2',
       'weekday_Mean_Encoding.temp_std_24_3',
       'weekday_Mean_Encoding.temp_mean_6_0.5',
       'weekday_Mean_Encoding.temp_mean_6_2',
       'weekday_Mean_Encoding.temp_mean_6_3',
       'weekday_Mean_Encoding.temp_mean_12_0.5',
       'weekday_Mean_Encoding.temp_mean_12_2',
       'weekday_Mean_Encoding.temp_mean_12_3',
       'weekday_Mean_Encoding.temp_mean_24_0.5',
       'weekday_Mean_Encoding.temp_mean_24_2',
       'weekday_Mean_Encoding.temp_mean_24_3',
       'month.week_Mean_Encoding.Distance',
       'month.week_Mean_Encoding.TemperatureLag1',
       'month.week_Mean_Encoding.TemperatureLag2',
       'month.week_Mean_Encoding.TemperatureLag24',
       'month.week_Mean_Encoding.TemperatureLag48',
       'month.week_Mean_Encoding.Temperature_2_Lag',
       'month.week_Mean_Encoding.Temperature_2_Lag1',
       'month.week_Mean_Encoding.Temperature_2_Lag2',
       'month.week_Mean_Encoding.Temperature_2_Lag24',
       'month.week_Mean_Encoding.Temperature_2_Lag48',
       'month.week_Mean_Encoding.Temperature_3_Lag',
       'month.week_Mean_Encoding.Temperature_3_Lag1',
       'month.week_Mean_Encoding.Temperature_3_Lag2',
       'month.week_Mean_Encoding.Temperature_3_Lag24',
       'month.week_Mean_Encoding.Temperature_3_Lag48',
       'month.week_Mean_Encoding.Temperature_0.5_Lag',
       'month.week_Mean_Encoding.Temperature_0.5_Lag1',
       'month.week_Mean_Encoding.Temperature_0.5_Lag2',
       'month.week_Mean_Encoding.Temperature_0.5_Lag24',
       'month.week_Mean_Encoding.Temperature_0.5_Lag48',
       'month.week_Mean_Encoding.DistanceLag1',
       'month.week_Mean_Encoding.DistanceLag2',
       'month.week_Mean_Encoding.DistanceLag24',
       'month.week_Mean_Encoding.DistanceLag48',
       'month.week_Mean_Encoding.Distance_2_Lag',
       'month.week_Mean_Encoding.Distance_2_Lag1',
       'month.week_Mean_Encoding.Distance_2_Lag2',
       'month.week_Mean_Encoding.Distance_2_Lag24',
       'month.week_Mean_Encoding.Distance_2_Lag48',
       'month.week_Mean_Encoding.Distance_3_Lag',
       'month.week_Mean_Encoding.Distance_3_Lag1',
       'month.week_Mean_Encoding.Distance_3_Lag2',
       'month.week_Mean_Encoding.Distance_3_Lag24',
       'month.week_Mean_Encoding.Distance_3_Lag48',
       'month.week_Mean_Encoding.Distance_0.5_Lag',
       'month.week_Mean_Encoding.Distance_0.5_Lag1',

In [12]:
box_data['Load_BoxCox']=box_data['box']

In [13]:
box_data = box_data.drop('box',axis=1)

In [14]:
sum(data.isnull().sum()>12)

225

In [15]:
#box_data.to_csv('06_2010_625_Variables_BoxL.csv')

In [16]:
train_set = box_data[box_data['Date']<'2011-01-01']
test_set = box_data[(box_data['Date']>='2011-01-01') & (box_data['Date']<'2012-01-01')]

In [17]:
train_set=train_set.dropna()

In [18]:
# X_train_set = train_set.drop(['Load_BoxCox','Load','Date','Hour','month','weekday','quarter','month.week','Day_Night_Time','Time_of_day'],axis=1).values
# Y_train_set = train_set['Load_BoxCox'].values

# X_test_set = test_set.drop(['Load_BoxCox','Load','Date','Hour','month','weekday','quarter','month.week','Day_Night_Time','Time_of_day'],axis=1).values
# Y_test_set = test_set['Load_BoxCox'].values

X_train_set = train_set.drop(['Load_BoxCox','Load','Date','Hour','month','weekday','quarter','month.week'],axis=1).values
Y_train_set = train_set['Load_BoxCox'].values

X_test_set = test_set.drop(['Load_BoxCox','Load','Date','Hour','month','weekday','quarter','month.week'],axis=1).values
Y_test_set = test_set['Load_BoxCox'].values

In [19]:
tset=train_set.drop(['Load_BoxCox','Load','Date','Hour','month','weekday','quarter','month.week'],axis=1)
tset.shape

(26256, 617)

In [20]:
# from sklearn.ensemble import GradientBoostingRegressor
# from sklearn.feature_selection import RFECV

In [21]:
# # params = {'n_estimators':100, 'max_depth':8, 'min_samples_split':500, 'min_sample_leaf':50,'learning_rate':.2, 
# #                 'loss':'ls'}
# GB = GradientBoostingRegressor()
# model = GB

# rfecv = RFECV(estimator=model, step=1, verbose=0)
# rfecv.fit(X_train_set, Y_train_set)

# var_ranking = pd.DataFrame(sorted(zip(map(lambda x: round(x), rfecv.ranking_), significant)),
#                             columns = ['ranking', 'variable'])
# pd.options.display.max_rows = 150
# print(var_ranking)

In [22]:
# var_selected=var_ranking[var_ranking.ranking==1]
# print(var_selected)

In [23]:
def custom_asymmetric_train(y_true, y_pred):
    residual = (y_true - y_pred).astype("float")
    grad = np.where(residual<0, -2*10.0*residual, -2*residual)
    hess = np.where(residual<0, 2*10.0, 2.0)
    return grad, hess

def custom_asymmetric_valid(y_true, y_pred):
    residual = (y_true - y_pred).astype("float")
    loss = np.where(residual < 0, (residual**2)*10.0, residual**2) 
    return "custom_asymmetric_eval", np.mean(loss), False

In [24]:
import lightgbm
# default lightgbm model with sklearn api
import numpy as np
gbm = lightgbm.LGBMRegressor() 

# updating objective function to custom
# default is "regression"
# also adding metrics to check different scores
gbm.set_params(**{'objective': custom_asymmetric_train}, metrics = ["mape"])

# fitting model 
gbm.fit(
    X_train_set,
    Y_train_set,
#     eval_set=[(X_test_set, Y_test_set)],
    eval_metric=custom_asymmetric_valid,
    verbose=False,
)

y_pred = gbm.predict(X_test_set)

/anaconda3/lib/python3.7/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

In [25]:
import matplotlib.pyplot as plt
lightgbm.plot_importance(gbm,height=0.2)
plt.show()

importance_type (string, optional (default="split")) – How the importance is calculated. If “split”, result contains numbers of times the feature is used in a model. If “gain”, result contains total gains of splits which use the feature.

In [26]:
# gbm.feature_importances_
var_rank=pd.DataFrame(tset.columns.values,columns=['Var_Name'])

In [27]:
rank=pd.Series(gbm.feature_importances_)
var_rank['rank']=rank

In [28]:
var_rank = var_rank.sort_values(by='rank',ascending=False)

In [29]:
var_rank=var_rank.reset_index().drop('index',axis=1)

In [30]:
var_rank[var_rank['rank']==0].Var_Name.values

array(['holiday.Distance_2_Lag24', 'holiday.Temperature_3_Lag1',
       'holiday.Distance_2_Lag2', 'holiday.Temperature_3_Lag2',
       'holiday.Distance_2_Lag1', 'Temperature_0.5_Lag2',
       'holiday.Temperature_0.5_Lag24', 'holiday.Temperature_0.5_Lag48',
       'holiday.Temperature_0.5_Lag', 'holiday.Distance_2_Lag',
       'Temperature_3_Lag48', 'holiday.Temperature_0.5_Lag2',
       'holiday.Temperature_0.5_Lag1', 'holiday.Temperature_3_Lag24',
       'Temperature_0.5_Lag', 'holiday.Temperature_3_Lag48',
       'Temperature_0.5_Lag1', 'DistanceLag1',
       'holiday.Temperature_3_Lag',
       'month.week_Mean_Encoding.temp_std_6_2', 'Distance_3_Lag2',
       'Distance_3_Lag24', 'month.week_Mean_Encoding.temp_std_12_3',
       'month.week_Mean_Encoding.temp_std_12_2', 'Distance_3_Lag48',
       'Distance_0.5_Lag', 'month.week_Mean_Encoding.temp_std_6_0.5',
       'Distance_3_Lag', 'month.week_Mean_Encoding.temp_min_24_3',
       'Distance_0.5_Lag1', 'Distance_0.5_Lag2',
       'month.week_Mean_Encoding.temp_min_12_3', 'Distance_0.5_Lag24',
       'Distance_0.5_Lag48', 'Distance_3_Lag1',
       'month.week_Mean_Encoding.temp_mean_6_2', 'Temperature_0.5_Lag24',
       'DistanceLag48', 'holiday.Temperature_2_Lag24',
       'holiday.Temperature_2_Lag2', 'holiday.Temperature_2_Lag1',
       'Temperature_0.5_Lag48', 'holiday.Distance_3_Lag', 'DistanceLag24',
       'Distance_2_Lag', 'month.week_Mean_Encoding.temp_mean_6_3',
       'Distance_2_Lag1', 'Distance_2_Lag2', 'Distance_2_Lag24',
       'month.week_Mean_Encoding.temp_mean_12_3',
       'month.week_Mean_Encoding.temp_mean_12_2', 'Distance_2_Lag48',
       'holiday.Distance_2_Lag48', 'quarter_Mean_Encoding.temp_std_12_3',
       'holiday.Distance_3_Lag1', 'holiday.temp_std_12_2',
       'holiday.temp_min_6_3', 'holiday.temp_min_12_0.5',
       'holiday.temp_min_12_2', 'holiday.temp_min_12_3',
       'holiday.temp_min_24_0.5', 'holiday.temp_min_24_2',
       'holiday.temp_min_24_3', 'holiday.temp_std_6_0.5',
       'holiday.temp_std_6_2', 'holiday.temp_std_6_3',
       'holiday.temp_std_12_0.5', 'holiday.temp_std_12_3',
       'holiday.temp_min_6_0.5', 'holiday.temp_std_24_0.5',
       'holiday.temp_std_24_2', 'holiday.temp_std_24_3',
       'holiday.temp_mean_6_0.5', 'holiday.temp_mean_6_2',
       'holiday.temp_mean_6_3', 'holiday.temp_mean_12_0.5',
       'holiday.temp_mean_12_2', 'holiday.temp_mean_12_3',
       'TemperatureLag1', 'holiday.temp_mean_24_2',
       'holiday.temp_min_6_2', 'holiday.temp_max_24_3',
       'holiday.Distance_3_Lag2', 'holiday.temp_min_12',
       'holiday.Distance_3_Lag24', 'holiday.Distance_3_Lag48',
       'holiday.Distance_0.5_Lag', 'holiday.Distance_0.5_Lag1',
       'holiday.Distance_0.5_Lag2', 'holiday.Distance_0.5_Lag24',
       'holiday.Distance_0.5_Lag48', 'Temperature_3_Lag24',
       'Temperature_3_Lag2', 'Temperature_3_Lag1', 'Temperature_3_Lag',
       'month.week_Mean_Encoding.temp_min_6_3', 'holiday.temp_max_24_2',
       'Temperature_2_Lag24', 'Temperature_2_Lag1', 'holiday.temp_mean_6',
       'Temperature_2_Lag', 'holiday.temp_max_6_0.5',
       'holiday.temp_max_6_2', 'holiday.temp_max_6_3',
       'holiday.temp_max_12_0.5', 'holiday.temp_max_12_2',
       'holiday.temp_max_12_3', 'holiday.temp_max_24_0.5',
       'Temperature_2_Lag48', 'temp_std_6_2', 'temp_mean_6',
       'weekday_Mean_Encoding.temp_min_12_3',
       'month_Mean_Encoding.Distance_3_Lag2',
       'month_Mean_Encoding.Distance_3_Lag1',
       'month_Mean_Encoding.Distance_3_Lag',
       'month_Mean_Encoding.Distance_2_Lag1',
       'month_Mean_Encoding.DistanceLag1',
       'month_Mean_Encoding.Temperature_3_Lag',
       'month_Mean_Encoding.Temperature_2_Lag1',
       'month_Mean_Encoding.TemperatureLag1',
       'Hour_Mean_Encoding.temp_mean_6_0.5',
       'Hour_Mean_Encoding.temp_std_6_3',
       'weekday_Mean_Encoding.temp_min_12_2',
       'Hour_Mean_Encoding.temp_max_6_3',
       'month_Mean_Encoding.Distance_3_Lag48',
       'Hour_Mean_Encoding.temp_std_6',
       'weekday_Mean_Encoding.temp_std_6_3',
       'Hour_Mean_Encoding.Distance_3_Lag24',
       'weekday_Mean_Encoding.temp_std_12_3',
       'Hour_Mean_Encoding.Distance_3_Lag',
       'Hour_Mean_Encoding.Distance_2_Lag1',
       'Hour_Mean_Encoding.Temperature_3_Lag24',
       'Hour_Mean_Encoding.Temperature_3_Lag2',
       'weekday_Mean_Encoding.temp_mean_6_3',
       'Hour_Mean_Encoding.Temperature_2_Lag24',
       'Hour_Mean_Encoding.Temperature_2_Lag1',
       'month_Mean_Encoding.Distance_3_Lag24',
       'month_Mean_Encoding.temp_mean_6',
       'Hour_Mean_Encoding.TemperatureLag2',
       'weekday_Mean_Encoding.Temperature_3_Lag1',
       'quarter_Mean_Encoding.temp_std_6_3',
       'quarter_Mean_Encoding.temp_std_6_2',
       'quarter_Mean_Encoding.temp_mean_6_0.5',
       'quarter_Mean_Encoding.temp_mean_6_3',
       'quarter_Mean_Encoding.temp_min_6_3',
       'quarter_Mean_Encoding.temp_min_6_2',
       'quarter_Mean_Encoding.temp_min_6_0.5',
       'quarter_Mean_Encoding.temp_mean_6', 'Distance',
       'quarter_Mean_Encoding.Distance_3_Lag1',
       'quarter_Mean_Encoding.Distance_3_Lag',
       'quarter_Mean_Encoding.DistanceLag2',
       'weekday_Mean_Encoding.Distance_3_Lag48',
       'weekday_Mean_Encoding.Temperature_0.5_Lag1',
       'quarter_Mean_Encoding.DistanceLag1',
       'quarter_Mean_Encoding.TemperatureLag1',
       'weekday_Mean_Encoding.Distance_2_Lag1',
       'weekday_Mean_Encoding.Distance_2_Lag2',
       'weekday_Mean_Encoding.Distance_2_Lag24',
       'month_Mean_Encoding.temp_mean_6_0.5',
       'weekday_Mean_Encoding.Distance_3_Lag',
       'weekday_Mean_Encoding.Distance_3_Lag1',
       'month_Mean_Encoding.temp_std_6_3',
       'weekday_Mean_Encoding.Distance_3_Lag24',
       'month.week_Mean_Encoding.Distance',
       'month.week_Mean_Encoding.TemperatureLag48', 'temp_max_6_0.5',
       'month.week_Mean_Encoding.temp_std_12', 'temp_std_12_0.5',
       'temp_std_6_3', 'quarter_Mean_Encoding.temp_std_12_2',
       'temp_std_6_0.5', 'month.week_Mean_Encoding.temp_max_6',
       'temp_min_24_3', 'temp_min_24_0.5', 'temp_min_12_3',
       'temp_min_12_2', 'temp_min_12_0.5', 'temp_min_6_3', 'temp_min_6_2',
       'month.week_Mean_Encoding.Distance_3_Lag48',
       'month.week_Mean_Encoding.temp_mean_6', 'temp_min_6_0.5',
       'temp_max_24_3', 'temp_max_24_2', 'temp_max_24_0.5',
       'month.week_Mean_Encoding.temp_max_6_3', 'temp_max_12_3',
       'temp_max_12_2', 'temp_max_12_0.5', 'temp_max_6_3', 'temp_max_6_2',
       'temp_std_12_2', 'month.week_Mean_Encoding.Distance_3_Lag24',
       'temp_mean_24_0.5', 'temp_std_24_2',
       'month.week_Mean_Encoding.Temperature_2_Lag1', 'temp_mean_12_3',
       'temp_mean_12_0.5', 'month.week_Mean_Encoding.Temperature_2_Lag48',
       'temp_mean_6_3', 'month.week_Mean_Encoding.Temperature_3_Lag1',
       'month.week_Mean_Encoding.Temperature_3_Lag24',
       'month.week_Mean_Encoding.Temperature_3_Lag48', 'temp_mean_6_0.5',
       'month.week_Mean_Encoding.Temperature_0.5_Lag1', 'temp_std_24_3',
       'temp_std_24_0.5', 'month.week_Mean_Encoding.Distance_3_Lag2',
       'month.week_Mean_Encoding.DistanceLag1',
       'month.week_Mean_Encoding.DistanceLag2',
       'month.week_Mean_Encoding.DistanceLag24', 'temp_std_12_3',
       'month.week_Mean_Encoding.Distance_2_Lag',
       'month.week_Mean_Encoding.Distance_2_Lag1',
       'month.week_Mean_Encoding.Distance_2_Lag2',
       'month.week_Mean_Encoding.Distance_2_Lag24',
       'month.week_Mean_Encoding.Distance_2_Lag48',
       'month.week_Mean_Encoding.Distance_3_Lag',
       'month.week_Mean_Encoding.Distance_3_Lag1',
       'holiday.temp_mean_24_3'], dtype=object)

In [32]:
new_selected_features_df = var_rank[var_rank['rank']>0]

In [33]:
new_selected_features_df

                                        Var_Name  rank
0                             Hour_Mean_Encoding   376
1                          weekday_Mean_Encoding   196
2                            month_Mean_Encoding   131
3                                            day   129
4           Hour_Mean_Encoding.Distance_0.5_Lag2    49
5                          quarter_Mean_Encoding    39
6          Hour_Mean_Encoding.Distance_0.5_Lag24    34
7            month_Mean_Encoding.temp_max_24_0.5    32
8                Hour_Mean_Encoding.temp_mean_24    23
9           Hour_Mean_Encoding.Distance_0.5_Lag1    22
10             month_Mean_Encoding.temp_max_24_2    21
11         month_Mean_Encoding.Distance_0.5_Lag2    21
12     month.week_Mean_Encoding.temp_mean_24_0.5    21
13         weekday_Mean_Encoding.temp_max_24_0.5    21
14         Hour_Mean_Encoding.Distance_0.5_Lag48    20
15         quarter_Mean_Encoding.temp_std_24_0.5    20
16                      month.week_Mean_Encoding    20
17        weekday_Mean_Encoding.TemperatureLag48    20
18      weekday_Mean_Encoding.Distance_0.5_Lag48    19
19          weekday_Mean_Encoding.temp_mean_24_2    19
20             weekday_Mean_Encoding.temp_min_24    17
21           month_Mean_Encoding.temp_std_24_0.5    17
22       weekday_Mean_Encoding.Distance_0.5_Lag2    17
23   weekday_Mean_Encoding.Temperature_0.5_Lag48    17
24      month.week_Mean_Encoding.temp_max_24_0.5    17
25                      holiday.TemperatureLag48    17
26         weekday_Mean_Encoding.temp_std_24_0.5    16
27         weekday_Mean_Encoding.temp_min_24_0.5    16
28        month_Mean_Encoding.Distance_0.5_Lag24    16
29             quarter_Mean_Encoding.temp_max_24    16
..                                           ...   ...
366      month_Mean_Encoding.Temperature_3_Lag24     1
367       month_Mean_Encoding.Temperature_2_Lag2     1
368             Hour_Mean_Encoding.temp_std_12_3     1
369         month_Mean_Encoding.TemperatureLag24     1
370                             TemperatureLag24     1
371             Hour_Mean_Encoding.temp_mean_6_3     1
372    quarter_Mean_Encoding.Temperature_3_Lag48     1
373     quarter_Mean_Encoding.Temperature_2_Lag1     1
374        quarter_Mean_Encoding.Distance_3_Lag2     1
375        Hour_Mean_Encoding.Temperature_3_Lag1     1
376                               temp_mean_24_2     1
377                               temp_mean_24_3     1
378          quarter_Mean_Encoding.temp_min_24_2     1
379          Hour_Mean_Encoding.TemperatureLag48     1
380         Hour_Mean_Encoding.Temperature_2_Lag     1
381           quarter_Mean_Encoding.temp_max_6_2     1
382         quarter_Mean_Encoding.temp_max_6_0.5     1
383            quarter_Mean_Encoding.temp_std_12     1
384                                temp_mean_6_2     1
385      quarter_Mean_Encoding.Distance_0.5_Lag1     1
386       quarter_Mean_Encoding.Distance_3_Lag48     1
387       quarter_Mean_Encoding.Distance_3_Lag24     1
388         Hour_Mean_Encoding.Temperature_3_Lag     1
389             Hour_Mean_Encoding.temp_mean_6_2     1
390       quarter_Mean_Encoding.Distance_2_Lag48     1
391        quarter_Mean_Encoding.Distance_2_Lag1     1
392          quarter_Mean_Encoding.DistanceLag24     1
393       quarter_Mean_Encoding.Distance_2_Lag24     1
394        quarter_Mean_Encoding.Distance_2_Lag2     1
395          quarter_Mean_Encoding.DistanceLag48     1

[396 rows x 2 columns]

In [34]:
new_selected_features_df

                                        Var_Name  rank
0                             Hour_Mean_Encoding   376
1                          weekday_Mean_Encoding   196
2                            month_Mean_Encoding   131
3                                            day   129
4           Hour_Mean_Encoding.Distance_0.5_Lag2    49
5                          quarter_Mean_Encoding    39
6          Hour_Mean_Encoding.Distance_0.5_Lag24    34
7            month_Mean_Encoding.temp_max_24_0.5    32
8                Hour_Mean_Encoding.temp_mean_24    23
9           Hour_Mean_Encoding.Distance_0.5_Lag1    22
10             month_Mean_Encoding.temp_max_24_2    21
11         month_Mean_Encoding.Distance_0.5_Lag2    21
12     month.week_Mean_Encoding.temp_mean_24_0.5    21
13         weekday_Mean_Encoding.temp_max_24_0.5    21
14         Hour_Mean_Encoding.Distance_0.5_Lag48    20
15         quarter_Mean_Encoding.temp_std_24_0.5    20
16                      month.week_Mean_Encoding    20
17        weekday_Mean_Encoding.TemperatureLag48    20
18      weekday_Mean_Encoding.Distance_0.5_Lag48    19
19          weekday_Mean_Encoding.temp_mean_24_2    19
20             weekday_Mean_Encoding.temp_min_24    17
21           month_Mean_Encoding.temp_std_24_0.5    17
22       weekday_Mean_Encoding.Distance_0.5_Lag2    17
23   weekday_Mean_Encoding.Temperature_0.5_Lag48    17
24      month.week_Mean_Encoding.temp_max_24_0.5    17
25                      holiday.TemperatureLag48    17
26         weekday_Mean_Encoding.temp_std_24_0.5    16
27         weekday_Mean_Encoding.temp_min_24_0.5    16
28        month_Mean_Encoding.Distance_0.5_Lag24    16
29             quarter_Mean_Encoding.temp_max_24    16
..                                           ...   ...
366      month_Mean_Encoding.Temperature_3_Lag24     1
367       month_Mean_Encoding.Temperature_2_Lag2     1
368             Hour_Mean_Encoding.temp_std_12_3     1
369         month_Mean_Encoding.TemperatureLag24     1
370                             TemperatureLag24     1
371             Hour_Mean_Encoding.temp_mean_6_3     1
372    quarter_Mean_Encoding.Temperature_3_Lag48     1
373     quarter_Mean_Encoding.Temperature_2_Lag1     1
374        quarter_Mean_Encoding.Distance_3_Lag2     1
375        Hour_Mean_Encoding.Temperature_3_Lag1     1
376                               temp_mean_24_2     1
377                               temp_mean_24_3     1
378          quarter_Mean_Encoding.temp_min_24_2     1
379          Hour_Mean_Encoding.TemperatureLag48     1
380         Hour_Mean_Encoding.Temperature_2_Lag     1
381           quarter_Mean_Encoding.temp_max_6_2     1
382         quarter_Mean_Encoding.temp_max_6_0.5     1
383            quarter_Mean_Encoding.temp_std_12     1
384                                temp_mean_6_2     1
385      quarter_Mean_Encoding.Distance_0.5_Lag1     1
386       quarter_Mean_Encoding.Distance_3_Lag48     1
387       quarter_Mean_Encoding.Distance_3_Lag24     1
388         Hour_Mean_Encoding.Temperature_3_Lag     1
389             Hour_Mean_Encoding.temp_mean_6_2     1
390       quarter_Mean_Encoding.Distance_2_Lag48     1
391        quarter_Mean_Encoding.Distance_2_Lag1     1
392          quarter_Mean_Encoding.DistanceLag24     1
393       quarter_Mean_Encoding.Distance_2_Lag24     1
394        quarter_Mean_Encoding.Distance_2_Lag2     1
395          quarter_Mean_Encoding.DistanceLag48     1

[396 rows x 2 columns]

In [35]:
new_selected_features_df.to_csv('LightGBM_Feature Selected.csv')

In [36]:
new_selected_features_df.shape

(396, 2)

In [37]:
y_pred
y_pred_t = pd.Series(y_pred)

In [38]:
y_pred_t

0       33.329713
1       33.023357
2       32.946649
3       33.103179
4       33.254359
5       33.257170
6       33.428589
7       33.746083
8       34.389373
9       34.952690
10      35.313483
11      35.336360
12      35.336360
13      35.411281
14      35.433906
15      35.363749
16      35.377625
17      35.506122
18      35.677153
19      35.656300
20      35.621361
21      35.527075
22      35.551170
23      34.867623
24      34.468443
25      34.145299
26      33.798110
27      33.717683
28      33.668192
29      33.843860
          ...
8730    35.616141
8731    35.686477
8732    35.574036
8733    35.569223
8734    34.900438
8735    34.631069
8736    33.715620
8737    33.527984
8738    33.301283
8739    33.211163
8740    33.185932
8741    33.196389
8742    33.379472
8743    33.706059
8744    33.648013
8745    34.153268
8746    34.217607
8747    34.244220
8748    34.203073
8749    34.169433
8750    34.184278
8751    34.150967
8752    34.142464
8753    34.328585
8754    34.306234
8755    34.189605
8756    34.352872
8757    34.302355
8758    34.064896
8759    33.889851
Length: 8760, dtype: float64

In [39]:
df=pd.DataFrame(Y_test_set,columns=['Test_Y'])
df['Pred_Y_Test']=y_pred

In [40]:
y_train_fit = gbm.predict(X_train_set)
y_pred_train = pd.Series(y_train_fit)

In [41]:
y_pred_train

0        35.494448
1        35.419060
2        35.058480
3        34.886122
4        34.791068
5        35.062048
6        35.371711
7        36.407383
8        36.730640
9        36.832093
10       36.920219
11       36.949395
12       36.734570
13       36.582126
14       36.642745
15       36.585159
16       36.563871
17       37.101410
18       37.488638
19       37.467581
20       37.273721
21       37.232316
22       36.534664
23       35.947110
24       35.290130
25       35.036282
26       34.505430
27       34.299646
28       34.318096
29       34.429451
           ...
26226    35.738234
26227    35.776472
26228    35.568856
26229    35.530930
26230    35.305986
26231    34.626151
26232    33.446833
26233    33.149623
26234    32.567974
26235    32.536648
26236    32.474443
26237    32.621352
26238    32.806808
26239    33.368407
26240    33.914302
26241    34.441129
26242    34.368595
26243    34.440040
26244    34.448432
26245    34.472915
26246    34.562946
26247    34.495096
26248    34.497652
26249    34.687403
26250    34.751395
26251    34.797885
26252    34.658833
26253    34.667487
26254    34.434067
26255    33.906033
Length: 26256, dtype: float64

In [42]:
df_t=pd.DataFrame(Y_train_set,columns=['Train_Y'])

In [43]:
df_t

         Train_Y
0      36.003434
1      35.533876
2      35.281840
3      35.141221
4      35.146125
5      35.329435
6      35.821265
7      36.614331
8      37.003447
9      37.096300
10     37.129202
11     37.143178
12     37.086483
13     37.006976
14     36.963854
15     36.893561
16     36.873611
17     37.329712
18     37.978562
19     37.935229
20     37.808360
21     37.573913
22     37.151556
23     36.461376
24     35.730356
25     35.233250
26     34.885184
27     34.719671
28     34.661168
29     34.800605
...          ...
26226  36.334859
26227  36.145345
26228  35.940701
26229  35.673301
26230  35.281031
26231  34.633941
26232  33.918251
26233  33.299875
26234  32.898180
26235  32.631254
26236  32.500554
26237  32.580770
26238  32.912941
26239  33.396546
26240  33.743507
26241  33.819360
26242  33.980434
26243  34.028876
26244  34.070881
26245  34.149137
26246  34.319015
26247  34.339101
26248  34.275233
26249  34.685790
26250  35.302030
26251  35.180396
26252  34.898529
26253  34.545033
26254  34.272601
26255  33.853929

[26256 rows x 1 columns]

In [44]:
df_t['Pred_Y_Train']=y_pred_train

In [45]:
df

         Test_Y  Pred_Y_Test
0     33.470880    33.329713
1     33.129259    33.023357
2     32.874523    32.946649
3     32.605030    33.103179
4     32.556459    33.254359
5     32.573684    33.257170
6     32.807236    33.428589
7     33.079915    33.746083
8     33.279874    34.389373
9     33.506470    34.952690
10    33.924575    35.313483
11    34.291012    35.336360
12    34.502919    35.336360
13    34.571602    35.411281
14    34.503780    35.433906
15    34.627977    35.363749
16    34.799765    35.377625
17    35.448832    35.506122
18    36.026308    35.677153
19    36.052942    35.656300
20    35.998854    35.621361
21    35.909218    35.527075
22    35.706940    35.551170
23    35.332656    34.867623
24    34.856777    34.468443
25    34.417385    34.145299
26    34.149137    33.798110
27    34.034247    33.717683
28    33.957941    33.668192
29    34.010061    33.843860
...         ...          ...
8730  35.858373    35.616141
8731  35.709283    35.686477
8732  35.532291    35.574036
8733  35.287496    35.569223
8734  34.960894    34.900438
8735  34.461523    34.631069
8736  33.788346    33.715620
8737  33.282733    33.527984
8738  32.925719    33.301283
8739  32.685532    33.211163
8740  32.611087    33.185932
8741  32.603010    33.196389
8742  32.860702    33.379472
8743  33.220625    33.706059
8744  33.393714    33.648013
8745  33.516753    34.153268
8746  33.758167    34.217607
8747  33.941720    34.244220
8748  34.109183    34.203073
8749  34.138495    34.169433
8750  34.079799    34.184278
8751  34.032457    34.150967
8752  34.188959    34.142464
8753  34.883515    34.328585
8754  35.440057    34.306234
8755  35.364010    34.189605
8756  35.145307    34.352872
8757  34.819917    34.302355
8758  34.570746    34.064896
8759  34.117184    33.889851

[8760 rows x 2 columns]

In [46]:
df.to_csv('test_result.csv')
df_t.to_csv('train_result.csv')